src/main/java/uk/nhs/ctp/entities/CaseCarePlan.java
src/main/java/uk/nhs/ctp/entities/Cases.java

Fixed mapping between Cases and CaseCarePlan so as to be bidirectional but with CaseCarePlan as the clear owner of the mapping.

CarePlan caseId mapping fix

---

EMS-UI/Dockerfile

Added a flag to disable host check for ng serve (webpack-dev-server) in the docker configuration.

Disable host check

---

EMS-UI/src/environments/environment.prod.ts

Updated the live EMS_API url for the production environment.

Update EMS url in EMS-UI

---

EMS-UI/.dockerignore
EMS-UI/Dockerfile
EMS-UI/nginx.conf
EMS-UI/src/app/app.module.ts

Updated to use `ng build` and deliver via `nginx` instead of doing `ng serve`.

EMS UI on nginx

---

src/main/java/uk/nhs/ctp/entities/Audit.java
src/main/java/uk/nhs/ctp/entities/AuditEntry.java
src/main/java/uk/nhs/ctp/entities/CaseImmunization.java
src/main/java/uk/nhs/ctp/entities/CaseMedication.java
src/main/java/uk/nhs/ctp/entities/CaseObservation.java
src/main/java/uk/nhs/ctp/entities/CaseParameter.java
src/main/java/uk/nhs/ctp/entities/Cases.java
src/main/java/uk/nhs/ctp/entities/CdssSupplier.java
src/main/java/uk/nhs/ctp/entities/CompositionEntity.java
src/main/java/uk/nhs/ctp/entities/EmsSupplier.java
src/main/java/uk/nhs/ctp/entities/QuestionResponse.java
src/main/java/uk/nhs/ctp/entities/ServiceDefinition.java
src/main/java/uk/nhs/ctp/entities/SupplierPartitioned.java
src/main/java/uk/nhs/ctp/entities/UserEntity.java

Not sure which data needs partitioning so I've added it to all of them except the two supplier tables.
Also not sure how we're supposed to be keeping track of supplier's so i've not added it as a foreign key or anything for now.

add partinitioning mapped superclass

---

EMS-UI/package-lock.json

Reverts UECIT/cactus-ems#7
turns out these are sub-dependencies :/

Revert "Bump acorn from 5.7.1 to 5.7.4 in /EMS-UI"

---

EMS-UI/src/app/pipe/role.ts
src/main/java/uk/nhs/ctp/SystemConstants.java
src/main/java/uk/nhs/ctp/controllers/CdssController.java
src/main/java/uk/nhs/ctp/controllers/UserController.java
src/main/java/uk/nhs/ctp/model/SupplierAccountDetails.java
src/main/java/uk/nhs/ctp/security/TokenAuthenticationService.java
src/main/java/uk/nhs/ctp/service/CdssSupplierService.java
src/main/java/uk/nhs/ctp/service/UserManagementService.java
src/main/resources/application.properties
src/test/java/uk/nhs/ctp/controllers/UserControllerTest.java
src/test/java/uk/nhs/ctp/service/UserManagementServiceTest.java

Save generated user in the EMS database. Also added a new role (ROLE_SUPPLIER_ADMIN) with mostly ROLE_NHS permissions.

Register suppliers - save new users in EMS DB

---

EMS-UI/package-lock.json
EMS-UI/src/app/model/emsSupplier.ts
EMS-UI/src/app/supplier-managment/ems-supplier/edit-supplier.component.html
EMS-UI/src/app/supplier-managment/ems-supplier/ems-supplier.component.html
EMS-UI/src/app/supplier-managment/ems-supplier/ems-supplier.component.spec.ts
EMS-UI/src/app/supplier-managment/ems-supplier/ems-supplier.component.ts
src/main/java/uk/nhs/ctp/entities/EmsSupplier.java
src/test/java/uk/nhs/ctp/controllers/EMSControllerComponentTest.java

This change adds the authToken field to the configuration interface for EMS instances.

Add support for setting and storing EMS Instance auth tokens

---

pom.xml
src/main/java/uk/nhs/ctp/controllers/AuthController.java
src/test/java/uk/nhs/ctp/controllers/AuthControllerComponentTest.java

Added an endpoint for retrieving the correct tokens needed for calling non-CACTUS EMS supplier endpoints.

Token exchange endpoint

---

EMS-UI/src/app/service/index.ts
EMS-UI/src/app/validation-report/validation-report.component.html
EMS-UI/src/app/validation-report/validation-report.component.spec.ts
EMS-UI/src/app/validation-report/validation-report.component.ts

Added selection capability to the validation report tables, including a checkbox to display the selection status.

Validation report - row selection

---

src/main/java/uk/nhs/ctp/auditFinder/finder/AWSAuditFinder.java
src/test/java/uk/nhs/ctp/auditFinder/AWSAuditFinderTest.java

We now query the "keyword" elastic search field for requestId.

ElasticSearch query field change

---

pom.xml
src/main/java/uk/nhs/ctp/service/ReportService.java
src/main/java/uk/nhs/ctp/service/ValidationService.java
src/test/java/uk/nhs/ctp/service/ValidationServiceTest.java

Adapted ValidationService to zipping up different audit operation types and added tests for the behaviour.
Below unresolved comments will be addressed in a further PR based on subtask [CDSCT-374](https://jira.digital.nhs.uk/browse/CDSCT-374).

Create audits zip file

---

src/main/java/uk/nhs/ctp/enums/ServiceCategory.java
src/main/java/uk/nhs/ctp/registry/AppointmentRegistry.java

Use a code from CareConnect-SDSJobRoleName value set.
The appointment was hard-coded as it's not obvious where this should come from. Not changed that, just updated the one value.

swap service category to use new valueset

---

.github/workflows/maven.yml

Separate webhooks will be invoked for develp and master branches

Add env-specific deployment hooks

---

src/main/java/uk/nhs/ctp/controllers/AuditController.java
src/main/java/uk/nhs/ctp/tkwvalidation/AuditDispatcher.java
src/main/java/uk/nhs/ctp/tkwvalidation/ValidationService.java
src/main/java/uk/nhs/ctp/tkwvalidation/model/AuditMetadata.java
src/test/java/uk/nhs/ctp/controllers/AuditControllerComponentTest.java

Thoughts on merging this change to support debugging?
Tested in staging using Postman and confirmed working.

Refactor audit validation to allow downloading evidence zip

---

pom.xml
src/main/java/uk/nhs/ctp/security/JWTLoginFilter.java

* Bumped common to use version with MDC logging of supplier id
* Added login success/failure message (CDSCT-450)

Supplier ID and user login logging

---

EMS-UI/src/app/triage/dos-display/dos-display.component.ts

The only actual change is the url from `?encounter=...` to `?encounterId=...` everything else is just a cosmetic refactor.
Not written unit tests for the component as didn't think it was worth it for such a tiny change - this component has a fair few dependencies to set up.

make encounter report get url spec compliant

---

src/main/java/uk/nhs/ctp/service/HealthcareServiceService.java
src/main/java/uk/nhs/ctp/transform/HealthcareServiceInTransformer.java

Removed extraneous encounterId query param in the handover HealthcareService endpoint.

Removed unnecessary encounterId param from EMS's $check-services

---

src/main/java/uk/nhs/ctp/resourceProvider/EncounterProvider.java
src/main/java/uk/nhs/ctp/service/search/SearchParameters.java
src/main/java/uk/nhs/ctp/service/search/SearchParametersTransformer.java
src/main/java/uk/nhs/ctp/transform/EncounterTransformer.java
src/test/java/uk/nhs/ctp/service/search/SearchParametersTransformerTest.java

Don't use CareConnect* as typename in DataRequirement and trigger search

Validation fixes

---

EMS-UI/src/app/validation-report/validation-report.component.css
EMS-UI/src/app/validation-report/validation-report.component.html
src/main/java/uk/nhs/ctp/controllers/UserController.java
src/main/java/uk/nhs/ctp/entities/ServiceDefinition.java
src/main/java/uk/nhs/ctp/entities/SupplierPartitioned.java
src/main/java/uk/nhs/ctp/entities/UserEntity.java
src/main/java/uk/nhs/ctp/security/CognitoService.java
src/main/java/uk/nhs/ctp/service/UserManagementService.java
src/main/java/uk/nhs/ctp/service/dto/ChangePasswordDTO.java
src/test/java/uk/nhs/ctp/service/UserManagementServiceTest.java

Allow admin users to reset supplier accounts

Account reset

---

EMS-UI/src/app/validation-report/validation-report.component.css
EMS-UI/src/app/validation-report/validation-report.component.html
src/main/java/uk/nhs/ctp/controllers/UserController.java
src/main/java/uk/nhs/ctp/entities/ServiceDefinition.java
src/main/java/uk/nhs/ctp/entities/SupplierPartitioned.java
src/main/java/uk/nhs/ctp/entities/UserEntity.java
src/main/java/uk/nhs/ctp/security/CognitoService.java
src/main/java/uk/nhs/ctp/service/UserManagementService.java
src/main/java/uk/nhs/ctp/service/dto/ChangePasswordDTO.java
src/test/java/uk/nhs/ctp/service/UserManagementServiceTest.java

* Scroll overflow for validation table
* Add endpoint to allow account reset
* Set supplier id length in db schema

Account reset (#118)
